### ISSUE TITLE
rolify and rails fixtures

### ISSUE THREAD

**Issue by daniely** [RolifyCommunity/rolify#337]
I'm using rails 4.2 and had a tough time with rolify and rails fixtures. After some mucking I finally got it working. Posting here incase someone else needs to do something similar and also creating this issue because it seems like the difficulty with fixtures is something rolify should "fix". But perhaps fixing simply means documenting somewhere. If that's desired I'd be happy to add a wiki.

To get rolify working with rails fixtures:

1. Create a `UsersRole` model in `models/users_role.rb`
```
# pretty much exclusively created for our fixtures to work
class UsersRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end
```
2. Create fixtures like so:
```
# users.yml
some_user:

# roles.yml - key here is to NOT include "resource" 
admin_role:
  name: :admin

# users_roles.yml
users_roles1:
  user: some_user
  role: admin
```
3. Add the fixtures to your tests
```
# in some test file
fixtures :users, :roles, :users_roles

users(:some_user).has_role? :admin # => true
```

**Comment by Crashtown** [comment]
I think that creating additional model only for fixtures is big overhead
but I agree that existing fixtures API is terrifying, I lost about 2-3 hours to persist object-scoped role to user for my integration tests.
Goal was to generate by fixtures a user model object with role scoped to dealership object defined in fixtures.
Key here to not try define "users:" in roles.yml fixtures, because I dont know why, but if I try to set users in fixture then attribute not set correctly.

example:
```yaml
# roles.yml
first_dealership_admin_role:
  name: :dealership_admin
  resource_id: 1
  resource_type: 'Dealership'

# users.yml
dealership_admin:
  id: 4
  email: 'da@test.test'
  encrypted_password: <%= Devise.bcrypt(User, 'password') %>
  dealership_id: 1
  roles: first_dealership_admin_role

# dealerships.yml
one:
  id: 1
  name: dealership_name
```
